(function(){
  const API_BASE='https://republica-api-1.onrender.com'.replace(/\/$/,'');
  const TOKEN_KEY='republica_admin_token_v1';
  const $=id=>document.getElementById(id);
  let settings=null;
  const token=()=>localStorage.getItem(TOKEN_KEY)||'';
  const setToken=value=>value?localStorage.setItem(TOKEN_KEY,value):localStorage.removeItem(TOKEN_KEY);
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const imageUrl=src=>/^media\//.test(src)?`${API_BASE}/${src}`:src;
  async function api(path,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${token()}`};if(options.body)headers['Content-Type']='application/json';const r=await fetch(`${API_BASE}${path}`,{...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Falha ao comunicar com o servidor.');return data;}
  function render(){['heroBadge','heroTitle','heroSubtitle','aboutText'].forEach(k=>$(k).value=settings[k]||'');$('photoList').innerHTML=settings.gallery.map((photo,i)=>`<article class="photo" data-index="${i}"><img src="${esc(imageUrl(photo.src))}" alt="Prévia da foto ${i+1}"><div class="field"><label>Legenda da foto ${i+1}</label><input data-caption value="${esc(photo.caption)}" maxlength="100"><div class="note">${esc(photo.src.split('/').pop())}</div></div><div class="photo-actions"><label class="small" for="photo-file-${i}">Trocar foto</label><input id="photo-file-${i}" type="file" accept="image/jpeg,image/png,image/webp"><button type="button" class="small danger" data-remove="${i}">Remover</button></div></article>`).join('')||'<p class="hint">Nenhuma foto. Adicione uma para exibir a galeria.</p>';
    $('photoList').querySelectorAll('[data-caption]').forEach(input=>input.addEventListener('input',()=>{settings.gallery[Number(input.closest('.photo').dataset.index)].caption=input.value;}));
    $('photoList').querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{if(settings.gallery.length<=1){alert('Mantenha pelo menos uma foto na galeria.');return;}settings.gallery.splice(Number(btn.dataset.remove),1);render();}));
    $('photoList').querySelectorAll('input[type=file]').forEach(input=>input.addEventListener('change',()=>uploadFile(input,Number(input.closest('.photo').dataset.index))));
  }
  function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Não foi possível ler a foto.'));reader.readAsDataURL(file);});}
  async function uploadFile(input,index){const file=input.files?.[0];if(!file)return;if(file.size>8*1024*1024){alert('A foto deve ter até 8 MB.');input.value='';return;}$('saveStatus').className='status';$('saveStatus').textContent='Enviando foto…';try{const dataUrl=await fileData(file);const result=await api('/api/admin/gallery-image',{method:'POST',body:JSON.stringify({dataUrl})});settings.gallery[index].src=result.src;render();$('saveStatus').className='status ok';$('saveStatus').textContent='Foto enviada. Salve as alterações para publicar na galeria.';}catch(e){$('saveStatus').className='status error';$('saveStatus').textContent=e.message;}}
  async function load(){ $('saveStatus').textContent='Carregando…';try{settings=await api('/api/admin/site-settings');render();$('loginCard').classList.add('hidden');$('editor').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('saveStatus').textContent='';}catch(e){$('saveStatus').className='status error';$('saveStatus').textContent=e.message;if(/não autorizado/i.test(e.message)){setToken('');showLogin();}}}
  function showLogin(){$('loginCard').classList.remove('hidden');$('editor').classList.add('hidden');$('logoutBtn').classList.add('hidden');}
  async function login(ev){ev.preventDefault();$('loginStatus').textContent='Entrando…';try{const r=await fetch(`${API_BASE}/api/admin/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Não foi possível entrar.');setToken(data.token);$('loginStatus').textContent='';await load();}catch(e){$('loginStatus').textContent=e.message;}}
  async function save(){['heroBadge','heroTitle','heroSubtitle','aboutText'].forEach(k=>settings[k]=$(k).value.trim());$('saveBtn').disabled=true;$('saveStatus').className='status';$('saveStatus').textContent='Salvando…';try{const result=await api('/api/admin/site-settings',{method:'PUT',body:JSON.stringify(settings)});settings=result.settings;render();$('saveStatus').className='status ok';$('saveStatus').textContent='Conteúdo salvo. O site já pode exibir as alterações.';}catch(e){$('saveStatus').className='status error';$('saveStatus').textContent=e.message;}finally{$('saveBtn').disabled=false;}}
  document.addEventListener('DOMContentLoaded',()=>{$('loginForm').addEventListener('submit',login);$('saveBtn').addEventListener('click',save);$('reloadBtn').addEventListener('click',load);$('addPhoto').addEventListener('click',()=>{settings.gallery.push({src:'assets/galeria/galeria-01.jpeg',caption:'Nova foto'});render();const idx=settings.gallery.length-1;$(`photo-file-${idx}`).click();});$('logoutBtn').addEventListener('click',()=>{setToken('');showLogin();$('loginStatus').textContent='Você saiu do painel.';});if(token())load();else showLogin();});
})();
